<?xml version="1.0" ?>
<!DOCTYPE FPTAptech [
        <!ELEMENT FPTAptech (Student)*>
        <!ELEMENT Student (Name,Age)>
        <!ELEMENT Name (FName,LName)>
        <!ELEMENT FName (#PCDATA)>
        <!ELEMENT LName (#PCDATA)>
        <!ELEMENT Age (#PCDATA)>
        ]>
<FPTAptech>
    <Student>
        <Name>
            <FName>Dinh</FName>
            <LName>Anh</LName>
        </Name>
        <Age>18</Age>
    </Student>
    <Student>
        <Name>
            <FName>Phan</FName>
            <LName>Tu</LName>
        </Name>
        <Age>22</Age>
    </Student>
    <Student>
        <Name>
            <FName>Kiet</FName>
            <LName>Do</LName>
        </Name>
        <Age>15</Age>
    </Student>
</FPTAptech>